version: "3"
services:
  gluetun:
    # https://github.com/bubuntux/nordvpn/issues/399#issuecomment-1547743008
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - REGION=Canada
    ports:
      - 8080:8080 # qbittorrent ui
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent # default username/password is admin/adminadmin.
    network_mode: service:gluetun
    depends_on:
      - gluetun
    volumes:
      - ./qbittorrent:/config
      - ./media:/media # Need to set download path to some folder in /media
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    volumes:
      - ./jackett/:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - ./radarr/:/config
      - ./media:/media # set root path to /media/movies but container needs /media
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - ./sonarr/:/config
      - ./media:/media # set root path to /media/shows but container needs /media
    ports:
      - 8989:8989
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      - PLEX_CLAIM= # from  https://plex.tv/claim
    volumes:
      - ./plex:/config # Plex library location. This can grow very large, 50gb+ is likely for a large collection.
      - ./media:/media
    ports:
      - 32400:32400 # for remote access
    restart: unless-stopped
