version: "3"
services:
  gluetun:
    # https://github.com/bubuntux/nordvpn/issues/399#issuecomment-1547743008
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - "VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}"
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - "REGION=${REGION}"
    ports:
      - 8080:8080 # qbittorrent ui
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent # default username/password is admin/adminadmin.
    network_mode: service:gluetun
    depends_on:
      - gluetun
    volumes:
      - ./qbittorrent:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set qbittorrent download path to /media/something
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    volumes:
      - ./jackett/:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - ./radarr/:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set radarr root path to /media/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - ./sonarr/:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set sonarr root path to /media/shows
    ports:
      - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    volumes:
      - ./bazarr:/config
      - "${MEDIA_ROOT_FOLDER}:/media"
    ports:
      - 6767:6767
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      - PLEX_CLAIM= # from  https://plex.tv/claim
    volumes:
      - ./plex:/config # Plex library location. This can grow very large, 50gb+ is likely for a large collection.
      - "${MEDIA_ROOT_FOLDER}:/media"
    ports:
      - 32400:32400 # for remote access
    restart: unless-stopped
