version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.35
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Canada
    ports:
      - 8080:8080 # qbittorrent ui
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent # default username/password is admin/adminadmin.
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./qbittorrent:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set qbittorrent download path to /media/something
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    volumes:
      - ./jackett/:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./radarr/:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set radarr root path to /media/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./sonarr/:/config
      - "${MEDIA_ROOT_FOLDER}:/media" # Set sonarr root path to /media/shows
    ports:
      - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./bazarr:/config
      - "${MEDIA_ROOT_FOLDER}:/media"
    ports:
      - 6767:6767
    restart: unless-stopped
